name: newmap2
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  carousel_pro:
    ^0.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: 0.14.0+2
  fancy_bottom_navigation: ^0.3.2
  google_maps_flutter: ^0.5.20+1
  font_awesome_flutter: ^8.5.0
  android_intent: ^0.3.2
  geolocator: ^5.1.2
  intl: ^0.16.0
  flip_card: ^0.4.1
  sticky_headers: ^0.1.8
  grouped_buttons: ^1.0.4
  direct_select: ^1.0.0
  url_launcher: ^5.1.2
  carousel_slider: ^1.3.1
  path_provider: ^1.2.0
  path: ^1.6.4
  flutter_pdf_viewer: ^0.0.2
  flutter_cupertino_localizations: ^1.0.1
  firebase_messaging: ^5.1.5
  auto_size_text: ^2.1.0
  photo_view: ^0.5.0
  video_player: ^0.10.2+1
  multi_image_picker: ^4.6.0-rc.3
  provider: ^3.1.0
  chewie: ^0.9.7
  firebase_ml_vision: ^0.9.3+8
  flutter_rating_bar: ^3.0.0
  webview_flutter: ^0.3.15+1
  configurable_expansion_tile: ^1.0.0
  side_header_list_view: ^0.0.4
  firebase_database: ^3.1.1
  fluro: ^1.5.1
  shared_preferences: ^0.5.6+2
  flutter_slidable: ^0.5.4
  qr_flutter: ^3.2.0
  cached_network_image: ^2.0.0
  firebase_storage: ^3.1.5
  fluttertoast: ^3.1.3
  cloud_firestore: ^0.13.0+1
  http: ^0.12.0
  sqflite: ^1.1.3
  badges: ^1.1.0
  flutter_spinkit: "^4.1.2"
  image_picker: ^0.6.3+4
  tflite: ^1.0.5
  mlkit: ^0.15.0
  flutter_native_image: ^0.0.5+2
  firebase_core: ^0.4.3+2
  time_formatter: ^1.0.0+5
  flutter_custom_dialog: ^1.0.16
  simple_pdf_viewer: ^0.2.2





dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the`
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/model_unquant.tflite
    - assets/labels.txt
    - assets/Inchcape.png
    - assets/crown-logo.png
    - assets/crown-logo_b.png
    - images/newBranch1.PNG
    - images/newBranch2.PNG
    - images/newBranch3.PNG
    - images/newBranch4.PNG
    - images/newBranch5.PNG
    - images/newBranch6.PNG
    - images/newBranch7.PNG
    - images/newBranch8.PNG
    - images/newBranch9.PNG
    - campanyLogo.png
    - images/inchcapesmalllogo.png
    - images/Inchcape-logo.png
    - images/title.png
    - images/crown-logo.png
    - images/News.jpg
    - images/News22.jpg
    - images/News4.jpg
    - images/News6.jpg
    - images/News7.jpg
    - images/News8.jpg
    - images/News9.jpg
    - images/News10.jpg
    - images/Alphard.jpg
    - images/maintenanceDiscount.jpg
    - images/Vellfire.jpg
    - images/bundleSales.jpg
    - images/EngineOil.jpg
    - images/EngineOil2.jpg
    - images/EngineOil3.jpg
    - images/HybridBattery.jpg
    - images/products_chemical.jpg
    - images/specialOffer.jpg
    - images/specialOffer2.jpg
    - images/specialOffer3.jpg
    - images/partsAccessories.jpg
    - images/TGMO.jpg
    - images/TGMO2.jpg
    - images/logopartclub.png
    - images/eye4HK.png
    - images/bg_uit.jpg
    - images/lexus.png
    - images/hino.png
    - images/toyota.png
    - images/Promotion_1.jpg
    - images/Promotion_2.jpg
    - images/Promotion_3.jpg
    - images/Promotion_4.jpg
    - assets/GeniuePart.pdf
    - assets/News.pdf
    - assets/News2.pdf
    - assets/News3.pdf
    - assets/News4.pdf
    - images/qrcode.jpg
    - images/orderreturn.jpg
    - assets/locale/localization_en
    - assets/locale/localization_zh
    - images/poster1.png
    - images/poster2.png
    - images/poster3.png
    - images/poster4.png
    - images/PromotionLeaflet1.jpg
    - images/PromotionLeaflet2.jpg
    - images/PromotionLeaflet3.jpg
    - images/PromotionLeaflet4.jpg
    - images/Diesel.jpg
    - images/Carburetor.jpg
    - images/Carburetor_Flange.jpg
    - images/Fuel_Float.jpg
    - images/Injection_Value.jpg
    - images/Thermostat.jpg
    - images/ThermostatA.jpg
    - images/ThermostatB.jpg
    - images/Fan_Blade.jpg
    - images/Fan_BladeA.jpg
    - images/Fan_BladeB.jpg
    - images/Carburetor_FlangeA.jpg
    - images/Carburetor_FlangeB.jpg
    - images/MITASU_motor_oil.jpg
    - images/OW-20_motor_oil.jpg
    - images/SN5W-40_motor_oil.jpg
    - images/SNCF10W-30_motor_oil.jpg
    - images/TF_TypeT-IV.jpg
    - images/SNOW-20_motor_oil.jpg
    - images/Coolant.jpg
    - images/Diesel_injector.jpg
    - images/TF_TypeT-IV.jpg
    - images/partsAccPDF2.jpg
    - images/PartsAccNews1.jpg
    - images/PartsAccNews2.jpg
    - images/PartsAccNews3.jpg
    - images/partsAccVideo1.mp4
    - images/partsAccVideo2.mp4
    - images/slogo_daihatsu.png
    - images/slogo_hino.png
    - images/slogo_lexus.png
    - images/slogo_toyota.png
    - images/t.png
    - images/t2.png
    - images/logopartclubchi.png
    - images/coupon.jpg
    - images/coupon2.jpg
    - assets/InchcapeLogo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
